#!/usr/bin/env python3
"""Regenerate agent/vocabulary.yaml from the committed compendium.

The tiered-vocabulary gate in `validate_compendium` reads
`agent/vocabulary.yaml`. This script derives the canonical term set from the
controlled paper-block fields of every compendium file (drafts and golds) so
the vocabulary stays in sync with what curation actually uses. Drift entries
are a small hand-maintained block preserved across regenerations.

Usage:
  python agent/build_vocabulary.py [--compendium DIR] [--out FILE] [--check]

`--check` regenerates in memory and exits non-zero if the on-disk file is
stale, without writing.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml  # type: ignore

from nasp_compendium.validate_compendium import VOCABULARY_FIELDS


_REPO_ROOT = Path(__file__).resolve().parent.parent
_DEFAULT_COMPENDIUM = _REPO_ROOT / "docs" / "compendium"
_DEFAULT_OUTPUT = _REPO_ROOT / "agent" / "vocabulary.yaml"

_DRIFT: dict[str, dict[str, str]] = {
    "cGAS": {"replacement": "CGAS", "reason": "use HGNC symbol"},
    "STING": {"replacement": "STING1", "reason": "use HGNC symbol"},
    "cGAS-STING1": {
        "replacement": "cGAS-STING",
        "reason": "pathway label uses gene-free form",
    },
}

_HEADER = (
    "# Canonical controlled vocabulary for the NASP compendium.\n"
    "# Generated by agent/build_vocabulary.py from docs/compendium.\n"
    "# Update the compendium or generator's _DRIFT block, then regenerate.\n"
    "# Run with --check to detect staleness.\n"
)


def collect_canonical_terms(compendium_dir: Path) -> dict[str, list[str]]:
    """Return sorted canonical terms per field across all compendium files."""
    terms_by_field: dict[str, set[str]] = {
        field: set() for field in VOCABULARY_FIELDS
    }
    for path in sorted(compendium_dir.glob("*.md")):
        data = yaml.safe_load(path.read_text())
        paper_block = data.get("paper") if isinstance(data, dict) else None
        if not isinstance(paper_block, dict):
            continue
        for paper in paper_block.values():
            if not isinstance(paper, dict):
                continue
            for field in VOCABULARY_FIELDS:
                values = paper.get(field)
                if isinstance(values, list):
                    terms_by_field[field].update(str(value) for value in values)
    return {field: sorted(terms_by_field[field]) for field in VOCABULARY_FIELDS}


def build_vocabulary(compendium_dir: Path) -> dict[str, Any]:
    """Return the vocabulary mapping (canonical + drift)."""
    return {
        "canonical": collect_canonical_terms(compendium_dir),
        "drift": _DRIFT,
    }


def render_vocabulary(vocabulary: dict[str, Any]) -> str:
    """Render the vocabulary mapping to YAML text with a provenance header."""
    body = yaml.safe_dump(vocabulary, sort_keys=True, default_flow_style=False)
    return _HEADER + body


def _parse_args(argv: list[str] | None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--compendium",
        type=Path,
        default=_DEFAULT_COMPENDIUM,
        help="Directory of compendium files (default: docs/compendium).",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=_DEFAULT_OUTPUT,
        help="Output path (default: agent/vocabulary.yaml).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the on-disk file is stale; do not write.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Generate or check vocabulary.yaml. Return a process exit code."""
    args = _parse_args(argv)
    rendered = render_vocabulary(build_vocabulary(args.compendium))

    if args.check:
        current = args.out.read_text() if args.out.exists() else ""
        if current == rendered:
            print(f"{args.out} is up to date.")
            return 0
        print(f"{args.out} is stale; run agent/build_vocabulary.py.")
        return 1

    args.out.write_text(rendered)
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
